#!/bin/bash

if ! command -v wasm-pack &> /dev/null
then
    echo "wasm-pack could not be found"
    echo "get it from: https://rustwasm.github.io/wasm-pack/installer/"
    exit 1
fi

wasm-pack build --target web --out-dir web/dist/
